"""added content

Revision ID: 14dfaddd4e48
Revises: 2cbe936a1817
Create Date: 2023-06-08 14:26:32.377866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14dfaddd4e48'
down_revision = '2cbe936a1817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('name', sa.String(), nullable=True))
    op.drop_index('ix_movies_price', table_name='movies')
    op.drop_index('ix_movies_title', table_name='movies')
    op.drop_column('movies', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.create_index('ix_movies_title', 'movies', ['title'], unique=False)
    op.create_index('ix_movies_price', 'movies', ['price'], unique=False)
    op.drop_column('movies', 'name')
    # ### end Alembic commands ###
