"""First Init

Revision ID: 7979a4026aff
Revises: 4d27d1e7aa4f
Create Date: 2023-06-08 13:33:28.864688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7979a4026aff'
down_revision = '4d27d1e7aa4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
